### PR TITLE
#162725244 Upgrade Django version from 1.0 to 2.1.5

### PR DESCRIPTION
**Pull request by kdaglas**
#### What does this PR do?
This PR is to upgrade the Django framework from 1.0 to 2.1.5

#### Description of Task to be completed?
Upgrade the Django framework version to fix the application's security issues and also to have the application have the full support of python 3.5 and above

#### How should this be manually tested?
- fetch this branch by running the command `git fetch origin ch-upgrade-django-162725244` in the terminal.
- check into the branch `git checkout ch-upgrade-django-162725244`.
- start the virtual environment `source venv/bin/activate`
- re-install requirements `pip install -r requirements.txt` 
- then make migrations by running `python manage.py makemigrations`
- migrate by running `python manage.py migrate`
- start the application `python manage.py runserver`

#### What are the relevant pivotal tracker stories?
[#162725244](https://www.pivotaltracker.com/story/show/162725244)

### CODE REVIEW

**Comment by MuhweziDeo** [comment]
It looks good

**Comment by armstrongsouljah** [comment]
Upgrade looks okay.

**Comment by ja-odur** [comment]
@kdaglas Please include how this PR can be manually tested in the PR description.

**Comment by ja-odur** [comment]
@kdaglas ensure that your commit body is bulleted.

**Comment by kdaglas** [comment]
@ja-odur I have bulleted the commit message

**Comment by kdaglas** [comment]
@ja-odur there are no tests so far since its simply an upgrade, and the first tests are to be implemented after the merge, that is why I excluded how to manually test it.

**Review by calvinpete — APPROVED** [review]
@kdaglas everything now looks fine.

**Review by MuhweziDeo — APPROVED** [review]
@kdaglas all good

**Review by armstrongsouljah — APPROVED** [review]
After reading through the changes, everything checks out.

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
