### PR TITLE
#162725257 Enable social login for the users to the application

### PR DESCRIPTION
**Pull request by kdaglas**
### What does this PR do?
Enable users to log into the application using Google, Facebook, and Twitter

### Description of Task to be completed?
- Create a file containing validation classes for the authentication tokens coming from Twitter, Facebook, and Google
- Add URLs that route to the endpoints accessing the login feature for the social links used to login in
- Create view classes for the social logins
- Install the required dependencies for Facebook, Google, and Twitter.
- Implement serialization classes that help store the data acquired from the created and decoded token if it is not already in the database
- Enable the user to login in into the application with his or her social media credentials by accessing their accounts.
 
### How should this be manually tested?
- Fetch and check out this branch with `git fetch origin ft-social-login-162725257` and `git checkout ft-social-login-162725257` 
- Create and activate your virtual environment with `python3 -m virtualenv <preferredname>` and `source <preferredname>/bin/activate`
- Install dependencies with `pip install -r requirements.txt`
- run migrations with `python manage.py migrate`
- Start the app by running `python manage.py runserver`
- Startup postman and add the routes endpoint `/api/users/<social_login>/`
- To use postman we need data to post which is the `auth_token` that the social platforms call Access Token, below is how to get them:

#### Facebook login /api/users/facebook-login/
- Go to the [Facebook developer](https://developers.facebook.com/tools/explorer/) site and log in your facebook account.
- At the top right corner is a `Get Started` link that when you click will take you through a series of instructions to creating an API app, follow the instructions to create it.
- After creating it, a dashboard is availed to you and on top in the navigation bar is a `Tools` link which you hover over and in the dropdown, select `Graph API Explorer`.
screenshot 2019-01-23 at 20 19 09

- A page with a form appears and to the right in that form is a button that says `Get Token`, click it, and a dropdown appears and in it select `Get User Access Token`
screenshot 2019-01-21 at 12 17 17 pm

- A dialogue box will pop up and in it check the email checkbox and then click the `Get the access token`
screenshot 2019-01-21 at 12 19 46 pm

- You can thereby use that token, by copying and pasting in postman as your `auth_token` and then post to access your endpoint
screenshot 2019-01-21 at 12 22 17 pm

#### Google login /api/users/google-login/
- Go to the developer page for google: [Google developers](https://developers.google.com/oauthplayground/)
- Navigate to the left-hand side and scroll through the list, select and click `Google OAuth2 API v1` or `Google+ API v1` and check all the options given there and then Authorize
screenshot 2019-01-21 at 5 01 24 pm

- When you authorize, google prompts you to login, choose the account to use to login so that you can access an `Authorization code` that is given to you.
screen shot 2019-01-24 at 2 01 04 am

- Click `Exchange authorization code for tokens` and two tokens are given to you, the `access_token` and the `id_token`, copy the id_token and paste it in your postman and post to access your endpoint
screenshot 2019-01-23 at 6 55 50 pm

#### Twitter login /api/users/twitter-login/
- Go to the [Twitter developer](https://developer.twitter.com/) page and login your twitter account
- In the navigation bar on your top right is a link `Apps` that you click and then navigate to a dashboard page where still on your right is a button prompting you to create an app that is if you don't have any.
screenshot 2019-01-23 at 10 06 14 pm

- Click the link and follow the instructions to create the app, here the time taken to review your authorization to create the app depends on how you answer the detailed information about how you are to use Twitter's API, if you say that you are going to use their tweets, information, and other Twitter-related material, then the authorization will take a very long time but if you specifically tell them that you only require the API to enable your users to log in to your app using Twitter, then time to review will be very short
screenshot 2019-01-23 at 10 22 36 pm

- When your app has been successfully reviewed and given access to operate, then navigate back to [Twitter developer](https://developer.twitter.com/) page and on your top right, hover over your username and a dropdown will show and in it select `Apps` which will take you to your created app that you can check out its `Details`.
screenshot 2019-01-23 at 11 09 34 pm

- On the detailed page, select Permissions and select the `Edit` button and then check the `Request email address from users` and save
screen shot 2019-01-24 at 2 08 43 am

- Then select `Keys and tokens` and that is where you get the access and the `access secret token` that you paste in postman to access that endpoint
screen shot 2019-01-24 at 1 50 37 am

### What are the relevant pivotal tracker stories?
[#162725257](https://www.pivotaltracker.com/story/show/162725257)

#### /api/users/facebook-login/
Endpoint for loging in a user through facebook
screen shot 2019-01-24 at 1 56 13 am

#### /api/users/twitter-login/
Endpoint for loging in a user through twitter
screen shot 2019-01-24 at 1 56 49 am

#### /api/users/google-login/
Endpoint for loging in a user through google
screen shot 2019-01-24 at 2 02 39 am

### CODE REVIEW

**Comment by ja-odur** [comment]
@kdaglas Please fix merge conflicts.

**Review by d-rita — COMMENTED** [review]
@kdaglas is there a postman collection we can use?

**Comment by mariamiah** [comment]
screen shot 2019-01-24 at 11 41 26 am
 can access the tokens but they seem not to be working, please look into this issue

**Review by MuhweziDeo — APPROVED** [review]

**Review by calvinpete — APPROVED** [review]
Works perfectly fine to me. Well done @kdaglas

**Review by mariamiah — APPROVED** [review]
LGTM

**Review by armstrongsouljah — APPROVED** [review]
LGTM

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
