### PR TITLE
#162725271  Enable user to share articles on different platforms

### PR DESCRIPTION
**Pull request by malfahad**
#### What does this PR do?
This PR adds functionality for articles to be sharable on different social media platforms

#### Description of Task to be completed?
Modify fetch articles endpoint to have 
```
{
"share_links": {
                "facebook": <facebook_share_link>,
                "gplus": <gplus_share_link>,
                "email": <email_share_link>
            }
}
```

#### How should this be manually tested?
 - fetch and checkout into this branch with: ` git fetch origin ft-share-articles-162725271 && git checkout ft-share-articles-162725271`
- activate your virtual environment
- Get articles from endpoint`{{url}}/api/articles` as an authenticated user.

##### Important Note: 
Sharable links for FB and google plus might not work well with localhost. use [this link](https://ah-backend-xmen.herokuapp.com) app to test is with a deployed app

#### What are the relevant pivotal tracker stories?
[#162725271](https://www.pivotaltracker.com/story/show/162725271)
#### Screenshots 

screen shot 2019-01-21 at 4 17 31 pm

#### POSTMAN

[Run in Postman](https://app.getpostman.com/run-collection/428039a8ebab19d7470c)

### CODE REVIEW

**Review by MuhweziDeo — DISMISSED** [review]
Looks good to me

**Comment by mariamiah** [comment]
Looks okay, try squashing the commits too

**Review by MuhweziDeo — DISMISSED** [review]
it's good to go. the links work now @malfahad

**Review by mariamiah — DISMISSED** [review]
Looks Good To Me

**Review by calvinpete — DISMISSED** [review]
@malfahad Works fine to me

**Review by d-rita — DISMISSED** [review]
LGTM

**Comment by ja-odur** [comment]
@malfahad Please refactor your code to fix the code duplications

**Review by MuhweziDeo — APPROVED** [review]

**Review by ja-odur — APPROVED** [review]
LGTM

**Comment by mariamiah** [comment]
LGTM

**Review by mariamiah — APPROVED** [review]

**Review by kdaglas — APPROVED** [review]
LGTM

**Pull request merged**
