### PR TITLE
#163583000 Add authentication to API swagger documentation

### PR DESCRIPTION
**Pull request by calvinpete**
#### What does this PR do?
This PR enables users to access protected routes on the API swagger documentation using their authentication credentials.

#### Description of Task to be completed?
- Add security definitions to the swagger settings to upload authorization functionality
- Append the swagger settings to the project's settings.py file
- Configure a few endpoints to capture their functionality as well as parameters

#### How should this be manually tested?

To Test this follow the steps below:
- Fetch and check into this branch with `git fetch origin bg-Add-authentication-to-swagger-163583000 && git checkout bg-Add-authentication-to-swagger-163583000`
- Activate your virtual environment by running `source venv/bin/activate`
- Start the application by running `python manage.py runserver`
- To access the documentation click this [link](http://127.0.0.1:8000/api/documentation/)
To access the protected routes
- Login a registered user then copy the Token from the response body.
- Click the Authorize button and input `Bearer` plus  __Copied Token__ then you can access the protected routes

#### What are the relevant pivotal tracker stories?
[#163583000](https://www.pivotaltracker.com/story/show/163583000)

### CODE REVIEW

**Review by ja-odur — DISMISSED** [review]
LGTM

**Review by ja-odur — DISMISSED** [review]
LGTM

**Comment by MuhweziDeo** [comment]
@calvinpete  It says invalid token
screen shot 2019-01-30 at 6 12 31 pm

**Review by MuhweziDeo — APPROVED** [review]
Good work @calvinpete

**Review by armstrongsouljah — APPROVED** [review]

**Review by ja-odur — APPROVED** [review]

**Pull request merged**
