### PR TITLE
#163754474: Implement Django CORS

### PR DESCRIPTION
**Pull request by mariamiah**
#### What does this PR do?
This implements Cross-origin Resource Sharing for the application

#### Description of Task to be completed?
* CORS allows developers to make cross-domain requests, similar to same-domain requests

#### How should this be manually tested?
* fetch this branch by running the command `git fetch origin bg-implement-django-CORS-163754474` and `bg-implement-django-CORS-163754474 ` in the terminal.
* Activate your virtual environment by running `source venv/bin/activate`
* Run `pip install -r requirements.txt`

#### What are the relevant pivotal tracker stories?
[#163754474](https://www.pivotaltracker.com/n/projects/2232225/stories/163754474)

### CODE REVIEW

**Review by armstrongsouljah — DISMISSED** [review]
LGTM!

**Review by MuhweziDeo — DISMISSED** [review]

**Review by kdaglas — DISMISSED** [review]
it is fine

**Review by calvinpete — DISMISSED** [review]

**Review by armstrongsouljah — APPROVED** [review]
LGTM

**Review by kdaglas — APPROVED** [review]

**Review by calvinpete — APPROVED** [review]

**Review by MuhweziDeo — APPROVED** [review]

**Comment by MuhweziDeo** [comment]
We tested this on a review app on heroku and it works fine

**Pull request merged**
