### PR TITLE
#162725277 Enable users to see their reading stats

### PR DESCRIPTION
**Pull request by kdaglas**
#### What does this PR do?
This PR enables a user to be able to see their reading statistics

#### Description of Task to be completed?
- create a read_stats field that will handle the data from the calculated number of times the article has been read.
- create a view file that will handle the endpoint that retrieves the calculated statistics.
- add logic for when the article is read

#### How should this be manually tested?
- Fetch this branch by running the command `git fetch origin ft-reading-stats-162725277` in the terminal and check into the branch `git checkout ft-reading-stats-162725277`
- Start the virtual environment `source venv/bin/activate`
- Migrate to add the read_stats field to the database, the field required for the data are initiated by typing this command: `python manage.py migrate`
- Start the application by running this command: `python manage.py runserver`
- create an article an then log out and login in as a different user and then read that aricle, you will see that the statistics change

#### Screenshots
Reading the aricle `/api/articles/<article-slug>`
screen shot 2019-01-30 at 2 32 50 pm

Getting read statistics for a user `/api/profiles/<username>/readstats`
screen shot 2019-01-30 at 2 32 20 pm

[Run in Postman](https://app.getpostman.com/run-collection/e692e9d1ae9e6885a02e)

#### Related story
[#162725277](https://www.pivotaltracker.com/story/show/162725277)

### CODE REVIEW

**Comment by MuhweziDeo** [comment]
@kdaglas  is the migration app specific like articles

**Comment by kdaglas** [comment]
@MuhweziDeo no it is not specific

**Comment by kdaglas** [comment]
am still working on this, so wait to test it out

**Comment by MuhweziDeo** [comment]
@kdaglas  Codeclimate file is to large

**Review by malfahad — DISMISSED** [review]
LGTM

**Comment by mariamiah** [comment]
Looks Good To Me

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by mariamiah — APPROVED** [review]
LGTM

**Review by armstrongsouljah — APPROVED** [review]
lgtm

**Pull request merged**
