### PR TITLE
#162725263 Users should be able to follow each other

### PR DESCRIPTION
**Pull request by d-rita**
**What does this PR do?**
This PR implements follow functionality in the app. A logged in user can follow and unfollow other users. A logged in user is also able see a list of followers and users they are following. 

**Description of Task to be completed?**
- Create a ProfileManager class to handle the follow/unfollow process for a logged in user. 
- Define methods in the UserProfileSerializer to return the number of followers and people following a given user. 
- Implement views to fetch the list of profiles of followers and users being followed. 
- Implement 3 endpoints, i.e.
1. `POST/api/profiles/<user-to-follow>/follow`
Enables a logged in user to follow another user. 
2. `DELETE/api/profiles/<user-to-unfollow>/follow`
Enables a logged in user to unfollow another user.
2.` GET/api/profiles/<username>/following`
Returns a list of profiles a user is following.
3. `GET/api/profiles/<username>/followers`
Returns a list of profiles following a user.

**How should this be manually tested?**
- Fetch and checkout this branch using `git fetch origin ft-follow-users-#162725263&& git checkout ft-follow-users-#162725263`
-Create virtual environment using `virtualenv <envname>` and activate it using `source <envname>/bin/activate`
- Run migrations with `python manage.py migrate profiles`
- To start the app, use `python manage.py runserver`
- After logging in a user, test the endpoints as shown below. 

**Screenshots**
**Follow a user**
follow
**Unfollowing a user**
unfollow
**Show profiles following a user**
following
**Show Follower profiles**
followers

**What are the relevant pivotal tracker stories?**
[#162725263](https://www.pivotaltracker.com/story/show/162725263)

**Postman Documentation**
[Run in Postman](https://app.getpostman.com/run-collection/ab068e647f6a4a69f2ed)

### CODE REVIEW

**Review by malfahad — DISMISSED** [review]
LGTM

**Comment by MuhweziDeo** [comment]
@d-rita make migrations should point to your app

**Comment by mariamiah** [comment]
LGTM

**Review by MuhweziDeo — DISMISSED** [review]
looks good to me @d-rita  Great stuff

**Comment by d-rita** [comment]
@ja-odur i have made the necessary changes

**Review by malfahad — APPROVED** [review]
LGTM

**Review by MuhweziDeo — APPROVED** [review]
looks good to me @d-rita

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
