### PR TITLE
#162725258: Users should be able to create their profiles

### PR DESCRIPTION
**Pull request by armstrongsouljah**
#### What does this PR do?
- Creates user profiles on successful registration
- Displays user profile
- Allows user to edit their profile details

##### Get Profile
`GET /api/profiles/:username`
- Returns the profile details of a registered user in JSON format

`PUT /api/profiles/:username/edit/`
- accepts JSON
- first_name
- last_name
- bio
- image `file-path`
- date_of_birth

#### How should this be manually tested?
- open up terminal
- change into the `Ah-backend-xmen` folder on your local machine
- run `$ git fetch --all` to get this branch created on your local machine`
- run `$ git checkout ft-create-user-profiles-162725258`
- activate your virtual environment by running `$ source venv/bin/activate`
- install dependencies by runinng `$ pip install -r requirements.txt`
**-add the following keys in your .env file to configure cloudinary**
- CLOUD_NAME = cloudinary-username
- API_KEY = cloudinary-api-key
- API_SECRET = cloudinary-secret-key
- CLOUDINARY_URL = cloudinary-base-url
**_N.B cloudinary credentials have been posted on our slack channel_**
- run `python manage.py migrate`
- run `python manage.py runserver`
- `register a new user by making a post request on localhost:8000/api/users`
- display the new user profile my making a GET request on `/api/profiles/newusername`

#### Relevant screenshots
Updating your profile
screenshot 2019-01-17 at 13 02 27

- Trying to update a profile that isn't yours.
screenshot 2019-01-17 at 13 04 52

- Viewing a profile detail
screenshot 2019-01-17 at 12 56 25

#### What are the relevant pivotal tracker stories?
- [Pivotal story](https://www.pivotaltracker.com/story/show/162725258)

### CODE REVIEW

**Review by MuhweziDeo — DISMISSED** [review]
like the way u used signals +1 @armstrongsouljah but the Views you are using +100 personally don't know how they work

**Comment by armstrongsouljah** [comment]
@MuhweziDeo thanks on the signals thumbs up, am still however blocked by @calvinpete who's task involves authentication and thus would require his code to be merged before I can allow a user to edit their profile.

On the views part, reach out anytime, am open to sharing the knowledge.

**Review by malfahad — DISMISSED** [review]
LGTM

**Comment by ja-odur** [comment]
@armstrongsouljah Please resolve merge conflicts

**Comment by mariamiah** [comment]
@armstrongsouljah  check your edit profile endpoint its failing,

**Comment by mariamiah** [comment]
screen shot 2019-01-16 at 7 17 32 pm
Add the instruction for checking into your branch too

**Comment by armstrongsouljah** [comment]
@ja-odur I resolved the conflicts locally but I am having a problem with my tests not being discovered. As soon as they are, I will push the code and my pr should be ready for merging.

**Comment by armstrongsouljah** [comment]
> @armstrongsouljah Please resolve merge conflicts

Confilcts have been resolved @ja-odur

**Comment by d-rita** [comment]
It seems you have not added the instruction to checkout your branch in the PR

**Comment by mariamiah** [comment]
Add the instruction for branch checkout and you are good to go

**Review by mariamiah — APPROVED** [review]
Looks Good To Me

**Review by calvinpete — COMMENTED** [review]
cloud_name =
api_key =
api_secret =
CLOUDINARY_URL =
**The above environment variables should be in upper case**

**Comment by armstrongsouljah** [comment]
> cloud_name =
> api_key =
> api_secret =
> CLOUDINARY_URL =
> **The above environment variables should be in upper case**
They were changed in the code. I forgot to edit the PR.

**Comment by armstrongsouljah** [comment]
@calvinpete I have edited the PR to reflect the environment variables used application wide.

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
