### PR TITLE
#162725270 Users should be able to see estimate reading time for articles

### PR DESCRIPTION
**Pull request by malfahad**
#### What does this PR do?
This PR adds functionality to estimate article read time based on article word count.

#### Description of Task to be completed?
This feature modifies the `/api/articles/<slug>` endpoint and introduce the field(s) below:
- `"read_time" :"5 mins"`

#### How should this be manually tested?
 - fetch and checkout into this branch with: ` git fetch origin ft-article-read-time-162725270 && git checkout ft-article-read-time-162725270`
- activate your virtual environment
- install dependencies with: ` pip install -r requirements.txt`
- run tests with `python manage.py test authors.apps.utils.tests.test_estimator`
- Get articles from endpoint`{{url}}/api/articles`
#### Screenshots
screen shot 2019-01-21 at 1 00 08 pm

#### What are the relevant pivotal tracker stories?
[#162725270](https://www.pivotaltracker.com/story/show/162725270)

#### Postman

[Run in Postman](https://app.getpostman.com/run-collection/fe5dc5538826abd99b3e#?env%5Bauthors-local%5D=W3sia2V5IjoiYmFzZS11cmwiLCJ2YWx1ZSI6IiIsImRlc2NyaXB0aW9uIjoiIiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJyZXNldC10b2tlbiIsInZhbHVlIjoiIiwiZGVzY3JpcHRpb24iOiIiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InRva2VuIiwidmFsdWUiOiIiLCJkZXNjcmlwdGlvbiI6IiIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoidXJsIiwidmFsdWUiOiIiLCJkZXNjcmlwdGlvbiI6IiIsImVuYWJsZWQiOnRydWV9XQ==)

### CODE REVIEW

**Review by MuhweziDeo — COMMENTED** [review]
@malfahad waiting to see this in action

**Comment by mariamiah** [comment]
I think it would be better if you squashed the commits

**Comment by ja-odur** [comment]
@malfahad Please the install requirement step and add postman documentation to the PR.

**Review by mariamiah — DISMISSED** [review]

**Comment by ja-odur** [comment]
@malfahad When I get a single article, I dont see the `read-time`

**Comment by malfahad** [comment]
@ja-odur  thanks for that. fixed it.

**Comment by mariamiah** [comment]
LGTM

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by mariamiah — APPROVED** [review]

**Review by armstrongsouljah — APPROVED** [review]
LGTM

**Pull request merged**
