### PR TITLE
#162725251 Integrate coveralls code coverage service

### PR DESCRIPTION
**Pull request by malfahad**
#### What does this PR do?
 This PR is to Integrate the project with coveralls code coverage

#### Description of Task to be completed?
 Integrate coveralls code coverage service to ensure tests cover the 
 entire project and display the coverage percentage in a badge in [ReadMe](https://github.com/andela/Ah-backend-xmen/blob/master/README.md)

#### How should this be manually tested?
- Navigate to this branch's [ReadMe file](https://github.com/andela/Ah-backend-xmen/blob/ch-integrate-coveralls-162725251/README.md)
- Click on the coverage badge which will take you to coverage report on coveralls.io

#### What are the relevant pivotal tracker stories?
[#162725251](https://www.pivotaltracker.com/story/show/162725251)

### CODE REVIEW

**Comment by MuhweziDeo** [comment]
Yeah I think its good to go did u add coveralls in the dependencies in requirements.txt

**Comment by kdaglas** [comment]
First add the coveralls dependency in the requirements file after the install.

**Review by kdaglas — COMMENTED** [review]
First, add the coveralls dependency in the requirements file after the install. since I don't see that change

**Comment by mariamiah** [comment]
The coveralls integration looks okay

**Review by armstrongsouljah — COMMENTED** [review]
Coveralls integration looks in order.

**Review by MuhweziDeo — DISMISSED** [review]
The badge is in place and you added dependencies in requirements

**Review by armstrongsouljah — APPROVED** [review]
LGTM.

**Review by calvinpete — APPROVED** [review]
@malfahad Looks fine to me.

**Review by MuhweziDeo — APPROVED** [review]
its good to go @malfahad

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
