### PR TITLE
#163956897 Email links should redirect to the front end

### PR DESCRIPTION
**Pull request by malfahad**
#### What does this PR do?
This PR fixes a bug in the backend. to allow get requests from links in the email to be redirected to the frontend.

#### How should this be manually tested?
- First `git fetch origin bg-redirect-frontend-163956897 and git checkout bg-redirect-frontend-163956897`
- then add `FRONTEND_BASE_URL` to the `.env` file.
- Then run tests with `python manage.py test`

- On signup, you will receive an email that redirects to the frontend
- On password reset request, you will receive an email that redirects to the frontend

#### What are the relevant pivotal tracker stories?
[#163956897](https://www.pivotaltracker.com/story/show/163956897)

### CODE REVIEW

**Review by kdaglas — DISMISSED** [review]
i have tested it, though am not sure if its ok to leave that commented out code, i think its ok because we might need it in the future as if implementation in the backend requires it but good work @malfahad

**Review by calvinpete — COMMENTED** [review]
@malfahad and @kdaglas
The commented out code does not justify its existence because it's out of context, no longer tested, linted or run.
So let's Just rely on the version control system(Github) to keep track of the code that once was.

**Review by MuhweziDeo — COMMENTED** [review]
Could we create a review app and test this out at @malfahad cc @armstrongsouljah

**Review by armstrongsouljah — APPROVED** [review]
Redirection works.

**Comment by malfahad** [comment]
@MuhweziDeo and @ja-odur , we have a review up running at `https://ah-backend-xmen.herokuapp.com`

**Review by calvinpete — APPROVED** [review]
Works fine to me

**Review by MuhweziDeo — APPROVED** [review]
everything works fine @ja-odur

**Review by mariamiah — APPROVED** [review]
LGTM

**Pull request merged**
